### ISSUE TITLE
Motion Modifiers

### ISSUE THREAD

**Issue by wrightpc** [kobbled/tp_plus#4]
I believe that there is some handling of motion modifiers but there are no examples of the syntax required. I specifically need to know how to add "MROT" to a joint move.

**Comment by kobbled** [comment]
Yes, not all the modifier have been added yet. See commit 9621e71 for updated modifiers. Usage can be seen in the tests added in [test_interpreter.rb](https://github.com/kobbled/tp_plus/commit/9621e71e073be55d417db07ffbab77d405918d5b#diff-5b8c6998441acced96da263152578a94). I discovered if any variables have the same name as the modifier tokens the interpreter will error out. For that reason I would prefer to be verbose in their naming, and for it to be less cryptic than what FANUC designates it as. However for now, both 'mrot', and 'minimal_rotation' will work. This isn't a big issue, but the error message TP-Plus gives is a bit unclear, so handling that error should be added in.

Right now the only examples are in the test_interpreter.rb it uses for unit testing. I'll open up an issue to add an examples folder with .tpp examples to make it more visible, and with better examples. For now if you are unsure of what functionality it has search through test_interpreter.rb, or see the token list in [token.rb](https://github.com/kobbled/tp_plus/blob/master/lib/tp_plus/token.rb), and then search for the token in test_interpreter.rb. 

If you have other  TP code snippets that are not interpreted by TP-Plus, or .tpp code gives you an error, please post the code snippet in a new issue, and I'll try and implement it as soon as I am able to. I'll get around to adding in the rest of the modifiers at a later time.
